# Generated by Django 5.1.2 on 2024-11-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
