# Generated by Django 5.1.2 on 2024-11-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_music_link_musician_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='picture',
            field=models.ImageField(blank=True, upload_to='musician_pictures/'),
        ),
    ]
